In [1]:
import numpy as np

A = np.arange(1, 21).reshape(4, 5)
print(A)
print(A.dtype)
print(A.ndim)
print(A.shape)
print(A.size)
print(A.itemsize)

B = A.reshape(5, 4)
print(B)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
int64
2
(4, 5)
20
8
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [2]:
a = np.array([[0,0,0],
              [10,10,10],
              [20,20,20],
              [30,30,30]])

b = np.array([0,1,2])

c = a + b
print(c)

mask = (c >= 22)
print(mask)

print(np.sum(c >= 22))

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]]
4


In [3]:
grades = np.array([[87,96,70],
                   [100,87,90],
                   [94,77,90],
                   [100,81,82]])

print(np.sum(grades))
print(np.min(grades))
print(np.max(grades))
print(np.mean(grades))
print(np.std(grades))
print(np.var(grades))

print(np.mean(grades, axis=0))
print(np.mean(grades, axis=1))
print(np.max(grades, axis=1))

1054
70
100
87.83333333333333
8.792357792739987
77.30555555555556
[95.25 85.25 83.  ]
[84.33333333 92.33333333 87.         87.66666667]
[ 96 100  94 100]


In [4]:
arr = np.array([[2,4,6],
                [1,3,5],
                [7,9,11]])

print(np.sum(arr, axis=1))
print(np.sum(arr, axis=0))
print(np.mean(arr))

[12  9 27]
[10 16 22]
5.333333333333333


In [5]:
A = np.array([[10,20,30],
              [40,50,60]])

B = np.array([1,2,3])

print(A + B)
print(A * 2)
print(A - 5)

[[11 22 33]
 [41 52 63]]
[[ 20  40  60]
 [ 80 100 120]]
[[ 5 15 25]
 [35 45 55]]


In [6]:
grades = np.array([[70,85,90],
                   [88,76,95],
                   [60,80,72]])

print(np.argmax(grades))
print(np.unravel_index(np.argmax(grades), grades.shape))

print(np.argmax(grades, axis=1))
print(np.argmin(grades, axis=0))

5
(np.int64(1), np.int64(2))
[2 2 1]
[2 1 2]
