In [1]:
import numpy as np

A = np.array([[5,8,2,7],
              [1,9,4,3],
              [6,0,11,10],
              [12,13,14,15]])

print(A[1])
print(A[:,2])
print(A[1:3,1:3])

[1 9 4 3]
[ 2  4 11 14]
[[ 9  4]
 [ 0 11]]


In [2]:
scores = np.array([[70,80,90],
                   [60,75,85],
                   [88,92,79],
                   [55,65,72]])

scores[:,1] += 5
print(scores)

scores[0] = [100,100,100]
print(scores)

scores[:,2] = 0
print(scores)

[[70 85 90]
 [60 80 85]
 [88 97 79]
 [55 70 72]]
[[100 100 100]
 [ 60  80  85]
 [ 88  97  79]
 [ 55  70  72]]
[[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]


In [3]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

v = np.array([2,4])

print(A * B)
print(np.dot(A,B))
print(A * v)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[ 2  8]
 [ 6 16]]


In [4]:
np.random.seed(0)

arr = np.random.randint(-5,6,(4,4))

values, counts = np.unique(arr, return_counts=True)
print(values)
print(counts)

print(np.unique(arr, axis=0))

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[1 1 1 3 1 2 1 2 2 1 1]
[[-3 -1  2  1]
 [ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [ 3  3  5 -4]]


In [5]:
a = np.array([[1,0,0],
              [1,0,0],
              [2,3,4]])

print(np.unique(a, axis=0))

[[1 0 0]
 [2 3 4]]


In [6]:
x = np.array([2,0,1,5,4,1,9])

print(np.argsort(x))
print(x[np.argsort(x)])

[1 2 5 0 4 3 6]
[0 1 1 2 4 5 9]


In [7]:
A = np.array([[3,8,1],
              [6,2,9]])

print(np.unravel_index(A.argmin(), A.shape))

(np.int64(0), np.int64(2))
